
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package dev.acousticjamm.underveil.init;

import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import java.util.List;
import java.util.ArrayList;

import dev.acousticjamm.underveil.block.YukoiWoodBlock;
import dev.acousticjamm.underveil.block.YukoiTrapDoorBlock;
import dev.acousticjamm.underveil.block.YukoiStairsBlock;
import dev.acousticjamm.underveil.block.YukoiSlabBlock;
import dev.acousticjamm.underveil.block.YukoiSaplingBlock;
import dev.acousticjamm.underveil.block.YukoiPressurePlateBlock;
import dev.acousticjamm.underveil.block.YukoiPlanksBlock;
import dev.acousticjamm.underveil.block.YukoiLogBlock;
import dev.acousticjamm.underveil.block.YukoiLeavesBlock;
import dev.acousticjamm.underveil.block.YukoiFenceGateBlock;
import dev.acousticjamm.underveil.block.YukoiFenceBlock;
import dev.acousticjamm.underveil.block.YukoiDoorBlock;
import dev.acousticjamm.underveil.block.YukoiButtonBlock;
import dev.acousticjamm.underveil.block.WithergrassBlock;
import dev.acousticjamm.underveil.block.WetOakWoodBlock;
import dev.acousticjamm.underveil.block.WetOakTrapdoorBlock;
import dev.acousticjamm.underveil.block.WetOakStairsBlock;
import dev.acousticjamm.underveil.block.WetOakSlabBlock;
import dev.acousticjamm.underveil.block.WetOakSaplingBlock;
import dev.acousticjamm.underveil.block.WetOakPressurePlateBlock;
import dev.acousticjamm.underveil.block.WetOakPlanksBlock;
import dev.acousticjamm.underveil.block.WetOakLogBlock;
import dev.acousticjamm.underveil.block.WetOakLeavesBlock;
import dev.acousticjamm.underveil.block.WetOakFenceGateBlock;
import dev.acousticjamm.underveil.block.WetOakFenceBlock;
import dev.acousticjamm.underveil.block.WetOakDoorBlock;
import dev.acousticjamm.underveil.block.WetOakButtonBlock;
import dev.acousticjamm.underveil.block.VenomiteOreBlock;
import dev.acousticjamm.underveil.block.VeilstoneWallBlock;
import dev.acousticjamm.underveil.block.VeilstoneStairsBlock;
import dev.acousticjamm.underveil.block.VeilstoneSlabBlock;
import dev.acousticjamm.underveil.block.VeilstonePressurePlateBlock;
import dev.acousticjamm.underveil.block.VeilstoneButtonBlock;
import dev.acousticjamm.underveil.block.VeilstoneBricksWallBlock;
import dev.acousticjamm.underveil.block.VeilstoneBricksStairsBlock;
import dev.acousticjamm.underveil.block.VeilstoneBricksSlabBlock;
import dev.acousticjamm.underveil.block.VeilstoneBricksBlock;
import dev.acousticjamm.underveil.block.VeilstoneBlock;
import dev.acousticjamm.underveil.block.VeilshroomBlock;
import dev.acousticjamm.underveil.block.VeilrockBlock;
import dev.acousticjamm.underveil.block.VeildaisyBlock;
import dev.acousticjamm.underveil.block.UnstabliteOreBlock;
import dev.acousticjamm.underveil.block.UnstabliteBlockBlock;
import dev.acousticjamm.underveil.block.UnderveilDimensionPortalBlock;
import dev.acousticjamm.underveil.block.ToxmolBlock;
import dev.acousticjamm.underveil.block.SmoothDustsandstoneBlock;
import dev.acousticjamm.underveil.block.SlowgrassBlock;
import dev.acousticjamm.underveil.block.SlowdirtBlock;
import dev.acousticjamm.underveil.block.SlipgrassBlock;
import dev.acousticjamm.underveil.block.SlipDirtBlock;
import dev.acousticjamm.underveil.block.SlidesandstoneWallBlock;
import dev.acousticjamm.underveil.block.SlidesandstoneStairsBlock;
import dev.acousticjamm.underveil.block.SlidesandstoneSlabBlock;
import dev.acousticjamm.underveil.block.SlidesandstoneBlock;
import dev.acousticjamm.underveil.block.SlidesandBlock;
import dev.acousticjamm.underveil.block.RoughveilWallBlock;
import dev.acousticjamm.underveil.block.RoughveilStairsBlock;
import dev.acousticjamm.underveil.block.RoughveilSlabBlock;
import dev.acousticjamm.underveil.block.RoughveilPressurePlateBlock;
import dev.acousticjamm.underveil.block.RoughveilButtonBlock;
import dev.acousticjamm.underveil.block.RoughveilBlock;
import dev.acousticjamm.underveil.block.RefleiWoodBlock;
import dev.acousticjamm.underveil.block.RefleiTrapDoorBlock;
import dev.acousticjamm.underveil.block.RefleiStairsBlock;
import dev.acousticjamm.underveil.block.RefleiSlabBlock;
import dev.acousticjamm.underveil.block.RefleiSaplingBlock;
import dev.acousticjamm.underveil.block.RefleiPressurePlateBlock;
import dev.acousticjamm.underveil.block.RefleiPlanksBlock;
import dev.acousticjamm.underveil.block.RefleiLogBlock;
import dev.acousticjamm.underveil.block.RefleiLeavesBlock;
import dev.acousticjamm.underveil.block.RefleiFenceGateBlock;
import dev.acousticjamm.underveil.block.RefleiFenceBlock;
import dev.acousticjamm.underveil.block.RefleiDoorBlock;
import dev.acousticjamm.underveil.block.RefleiButtonBlock;
import dev.acousticjamm.underveil.block.PoigrassBlock;
import dev.acousticjamm.underveil.block.PoidirtBlock;
import dev.acousticjamm.underveil.block.MoslinWoodBlock;
import dev.acousticjamm.underveil.block.MoslinTrapdoorBlock;
import dev.acousticjamm.underveil.block.MoslinStairsBlock;
import dev.acousticjamm.underveil.block.MoslinSlabBlock;
import dev.acousticjamm.underveil.block.MoslinSaplingBlock;
import dev.acousticjamm.underveil.block.MoslinPressurePlateBlock;
import dev.acousticjamm.underveil.block.MoslinPlanksBlock;
import dev.acousticjamm.underveil.block.MoslinLogBlock;
import dev.acousticjamm.underveil.block.MoslinLeavesBlock;
import dev.acousticjamm.underveil.block.MoslinFenceGateBlock;
import dev.acousticjamm.underveil.block.MoslinFenceBlock;
import dev.acousticjamm.underveil.block.MoslinDoorBlock;
import dev.acousticjamm.underveil.block.MoslinButtonBlock;
import dev.acousticjamm.underveil.block.LandmineBlock;
import dev.acousticjamm.underveil.block.JumpgrassBlock;
import dev.acousticjamm.underveil.block.JumpdirtBlock;
import dev.acousticjamm.underveil.block.JumpPadBlock;
import dev.acousticjamm.underveil.block.IronVeilstoneBlock;
import dev.acousticjamm.underveil.block.IncancentineOreBlock;
import dev.acousticjamm.underveil.block.IncancentineBlockBlock;
import dev.acousticjamm.underveil.block.GoldVeilstoneBlock;
import dev.acousticjamm.underveil.block.ForgingTableBlock;
import dev.acousticjamm.underveil.block.ForceTNTBlock;
import dev.acousticjamm.underveil.block.FlismolBlock;
import dev.acousticjamm.underveil.block.FlisgrassBlock;
import dev.acousticjamm.underveil.block.FlisdirtBlock;
import dev.acousticjamm.underveil.block.FlasmolBlock;
import dev.acousticjamm.underveil.block.FlashFurnaceBlock;
import dev.acousticjamm.underveil.block.EtherChestBlock;
import dev.acousticjamm.underveil.block.EtherBlockBlock;
import dev.acousticjamm.underveil.block.DustsandstonestairsBlock;
import dev.acousticjamm.underveil.block.DustsandstoneslabBlock;
import dev.acousticjamm.underveil.block.DustsandstoneWallBlock;
import dev.acousticjamm.underveil.block.DustquicksandBlock;
import dev.acousticjamm.underveil.block.DustSandstoneBlock;
import dev.acousticjamm.underveil.block.DustSandBlock;
import dev.acousticjamm.underveil.block.DiamondVeilstoneBlock;
import dev.acousticjamm.underveil.block.DeepveilWallBlock;
import dev.acousticjamm.underveil.block.DeepveilStairsBlock;
import dev.acousticjamm.underveil.block.DeepveilSlabBlock;
import dev.acousticjamm.underveil.block.DeepveilPressurePlateBlock;
import dev.acousticjamm.underveil.block.DeepveilButtonBlock;
import dev.acousticjamm.underveil.block.DeepveilBlock;
import dev.acousticjamm.underveil.block.DarkiteTrapdoorBlock;
import dev.acousticjamm.underveil.block.DarkiteOreBlock;
import dev.acousticjamm.underveil.block.DarkiteDoorBlock;
import dev.acousticjamm.underveil.block.CutDustsandstoneBlock;
import dev.acousticjamm.underveil.block.ChisledDustsandstoneBlock;
import dev.acousticjamm.underveil.block.BurnstoneoreBlock;
import dev.acousticjamm.underveil.block.BurnstoneBlockBlock;
import dev.acousticjamm.underveil.block.BloodstoneTrapdoorBlock;
import dev.acousticjamm.underveil.block.BloodstoneOreBlock;
import dev.acousticjamm.underveil.block.BloodstoneDoorBlock;
import dev.acousticjamm.underveil.block.BloodstoneBlockBlock;
import dev.acousticjamm.underveil.block.BerrycaneBlock;
import dev.acousticjamm.underveil.block.AshgravelBlock;
import dev.acousticjamm.underveil.block.AshWoodBlock;
import dev.acousticjamm.underveil.block.AshTrapdoorBlock;
import dev.acousticjamm.underveil.block.AshStairsBlock;
import dev.acousticjamm.underveil.block.AshSlabBlock;
import dev.acousticjamm.underveil.block.AshSaplingBlock;
import dev.acousticjamm.underveil.block.AshPressurePlateBlock;
import dev.acousticjamm.underveil.block.AshPlanksBlock;
import dev.acousticjamm.underveil.block.AshLogBlock;
import dev.acousticjamm.underveil.block.AshLeavesBlock;
import dev.acousticjamm.underveil.block.AshFenceGateBlock;
import dev.acousticjamm.underveil.block.AshFenceBlock;
import dev.acousticjamm.underveil.block.AshDoorBlock;
import dev.acousticjamm.underveil.block.AshCrateBlock;
import dev.acousticjamm.underveil.block.AshButtonBlock;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class UnderveilModBlocks {
	private static final List<Block> REGISTRY = new ArrayList<>();
	public static final Block ASH_WOOD = register(new AshWoodBlock());
	public static final Block ASH_LOG = register(new AshLogBlock());
	public static final Block ASH_PLANKS = register(new AshPlanksBlock());
	public static final Block ASH_CRATE = register(new AshCrateBlock());
	public static final Block ASH_STAIRS = register(new AshStairsBlock());
	public static final Block ASH_SLAB = register(new AshSlabBlock());
	public static final Block ASH_FENCE = register(new AshFenceBlock());
	public static final Block ASH_FENCE_GATE = register(new AshFenceGateBlock());
	public static final Block ASH_PRESSURE_PLATE = register(new AshPressurePlateBlock());
	public static final Block ASH_BUTTON = register(new AshButtonBlock());
	public static final Block ASH_DOOR = register(new AshDoorBlock());
	public static final Block ASH_TRAPDOOR = register(new AshTrapdoorBlock());
	public static final Block ASH_LEAVES = register(new AshLeavesBlock());
	public static final Block ASH_SAPLING = register(new AshSaplingBlock());
	public static final Block SLIPGRASS = register(new SlipgrassBlock());
	public static final Block SLIP_DIRT = register(new SlipDirtBlock());
	public static final Block MOSLIN_WOOD = register(new MoslinWoodBlock());
	public static final Block MOSLIN_LOG = register(new MoslinLogBlock());
	public static final Block MOSLIN_PLANKS = register(new MoslinPlanksBlock());
	public static final Block MOSLIN_STAIRS = register(new MoslinStairsBlock());
	public static final Block MOSLIN_SLAB = register(new MoslinSlabBlock());
	public static final Block MOSLIN_FENCE = register(new MoslinFenceBlock());
	public static final Block MOSLIN_FENCE_GATE = register(new MoslinFenceGateBlock());
	public static final Block MOSLIN_PRESSURE_PLATE = register(new MoslinPressurePlateBlock());
	public static final Block MOSLIN_BUTTON = register(new MoslinButtonBlock());
	public static final Block MOSLIN_DOOR = register(new MoslinDoorBlock());
	public static final Block MOSLIN_TRAPDOOR = register(new MoslinTrapdoorBlock());
	public static final Block MOSLIN_LEAVES = register(new MoslinLeavesBlock());
	public static final Block MOSLIN_SAPLING = register(new MoslinSaplingBlock());
	public static final Block JUMPGRASS = register(new JumpgrassBlock());
	public static final Block JUMPDIRT = register(new JumpdirtBlock());
	public static final Block WET_OAK_WOOD = register(new WetOakWoodBlock());
	public static final Block WET_OAK_LOG = register(new WetOakLogBlock());
	public static final Block WET_OAK_PLANKS = register(new WetOakPlanksBlock());
	public static final Block WET_OAK_STAIRS = register(new WetOakStairsBlock());
	public static final Block WET_OAK_SLAB = register(new WetOakSlabBlock());
	public static final Block WET_OAK_FENCE = register(new WetOakFenceBlock());
	public static final Block WET_OAK_FENCE_GATE = register(new WetOakFenceGateBlock());
	public static final Block WET_OAK_PRESSURE_PLATE = register(new WetOakPressurePlateBlock());
	public static final Block WET_OAK_BUTTON = register(new WetOakButtonBlock());
	public static final Block WET_OAK_DOOR = register(new WetOakDoorBlock());
	public static final Block WET_OAK_TRAPDOOR = register(new WetOakTrapdoorBlock());
	public static final Block WET_OAK_LEAVES = register(new WetOakLeavesBlock());
	public static final Block WET_OAK_SAPLING = register(new WetOakSaplingBlock());
	public static final Block FLISGRASS = register(new FlisgrassBlock());
	public static final Block FLISDIRT = register(new FlisdirtBlock());
	public static final Block REFLEI_WOOD = register(new RefleiWoodBlock());
	public static final Block REFLEI_LOG = register(new RefleiLogBlock());
	public static final Block REFLEI_PLANKS = register(new RefleiPlanksBlock());
	public static final Block REFLEI_STAIRS = register(new RefleiStairsBlock());
	public static final Block REFLEI_SLAB = register(new RefleiSlabBlock());
	public static final Block REFLEI_FENCE = register(new RefleiFenceBlock());
	public static final Block REFLEI_FENCE_GATE = register(new RefleiFenceGateBlock());
	public static final Block REFLEI_PRESSURE_PLATE = register(new RefleiPressurePlateBlock());
	public static final Block REFLEI_BUTTON = register(new RefleiButtonBlock());
	public static final Block REFLEI_DOOR = register(new RefleiDoorBlock());
	public static final Block REFLEI_TRAP_DOOR = register(new RefleiTrapDoorBlock());
	public static final Block REFLEI_LEAVES = register(new RefleiLeavesBlock());
	public static final Block REFLEI_SAPLING = register(new RefleiSaplingBlock());
	public static final Block POIGRASS = register(new PoigrassBlock());
	public static final Block WITHERGRASS = register(new WithergrassBlock());
	public static final Block POIDIRT = register(new PoidirtBlock());
	public static final Block YUKOI_WOOD = register(new YukoiWoodBlock());
	public static final Block YUKOI_LOG = register(new YukoiLogBlock());
	public static final Block YUKOI_PLANKS = register(new YukoiPlanksBlock());
	public static final Block YUKOI_STAIRS = register(new YukoiStairsBlock());
	public static final Block YUKOI_SLAB = register(new YukoiSlabBlock());
	public static final Block YUKOI_FENCE = register(new YukoiFenceBlock());
	public static final Block YUKOI_FENCE_GATE = register(new YukoiFenceGateBlock());
	public static final Block YUKOI_PRESSURE_PLATE = register(new YukoiPressurePlateBlock());
	public static final Block YUKOI_BUTTON = register(new YukoiButtonBlock());
	public static final Block YUKOI_DOOR = register(new YukoiDoorBlock());
	public static final Block YUKOI_TRAP_DOOR = register(new YukoiTrapDoorBlock());
	public static final Block YUKOI_LEAVES = register(new YukoiLeavesBlock());
	public static final Block YUKOI_SAPLING = register(new YukoiSaplingBlock());
	public static final Block SLOWGRASS = register(new SlowgrassBlock());
	public static final Block SLOWDIRT = register(new SlowdirtBlock());
	public static final Block VEILROCK = register(new VeilrockBlock());
	public static final Block VEILSTONE = register(new VeilstoneBlock());
	public static final Block VEILSTONE_STAIRS = register(new VeilstoneStairsBlock());
	public static final Block VEILSTONE_SLAB = register(new VeilstoneSlabBlock());
	public static final Block VEILSTONE_WALL = register(new VeilstoneWallBlock());
	public static final Block VEILSTONE_PRESSURE_PLATE = register(new VeilstonePressurePlateBlock());
	public static final Block VEILSTONE_BUTTON = register(new VeilstoneButtonBlock());
	public static final Block DEEPVEIL = register(new DeepveilBlock());
	public static final Block DEEPVEIL_STAIRS = register(new DeepveilStairsBlock());
	public static final Block DEEPVEIL_SLAB = register(new DeepveilSlabBlock());
	public static final Block DEEPVEIL_WALL = register(new DeepveilWallBlock());
	public static final Block DEEPVEIL_PRESSURE_PLATE = register(new DeepveilPressurePlateBlock());
	public static final Block DEEPVEIL_BUTTON = register(new DeepveilButtonBlock());
	public static final Block ROUGHVEIL = register(new RoughveilBlock());
	public static final Block VEILSTONE_BRICKS = register(new VeilstoneBricksBlock());
	public static final Block VEILSTONE_BRICKS_STAIRS = register(new VeilstoneBricksStairsBlock());
	public static final Block VEILSTONE_BRICKS_SLAB = register(new VeilstoneBricksSlabBlock());
	public static final Block VEILSTONE_BRICKS_WALL = register(new VeilstoneBricksWallBlock());
	public static final Block DUST_SAND = register(new DustSandBlock());
	public static final Block DUSTQUICKSAND = register(new DustquicksandBlock());
	public static final Block DUST_SANDSTONE = register(new DustSandstoneBlock());
	public static final Block CHISLED_DUSTSANDSTONE = register(new ChisledDustsandstoneBlock());
	public static final Block CUT_DUSTSANDSTONE = register(new CutDustsandstoneBlock());
	public static final Block SMOOTH_DUSTSANDSTONE = register(new SmoothDustsandstoneBlock());
	public static final Block DUSTSANDSTONESTAIRS = register(new DustsandstonestairsBlock());
	public static final Block DUSTSANDSTONESLAB = register(new DustsandstoneslabBlock());
	public static final Block DUSTSANDSTONE_WALL = register(new DustsandstoneWallBlock());
	public static final Block SLIDESAND = register(new SlidesandBlock());
	public static final Block SLIDESANDSTONE = register(new SlidesandstoneBlock());
	public static final Block SLIDESANDSTONE_STAIRS = register(new SlidesandstoneStairsBlock());
	public static final Block SLIDESANDSTONE_SLAB = register(new SlidesandstoneSlabBlock());
	public static final Block SLIDESANDSTONE_WALL = register(new SlidesandstoneWallBlock());
	public static final Block ASHGRAVEL = register(new AshgravelBlock());
	public static final Block FORGING_TABLE = register(new ForgingTableBlock());
	public static final Block FLASH_FURNACE = register(new FlashFurnaceBlock());
	public static final Block BURNSTONEORE = register(new BurnstoneoreBlock());
	public static final Block BURNSTONE_BLOCK = register(new BurnstoneBlockBlock());
	public static final Block VENOMITE_ORE = register(new VenomiteOreBlock());
	public static final Block INCANCENTINE_ORE = register(new IncancentineOreBlock());
	public static final Block INCANCENTINE_BLOCK = register(new IncancentineBlockBlock());
	public static final Block BLOODSTONE_ORE = register(new BloodstoneOreBlock());
	public static final Block BLOODSTONE_BLOCK = register(new BloodstoneBlockBlock());
	public static final Block BLOODSTONE_DOOR = register(new BloodstoneDoorBlock());
	public static final Block BLOODSTONE_TRAPDOOR = register(new BloodstoneTrapdoorBlock());
	public static final Block DARKITE_ORE = register(new DarkiteOreBlock());
	public static final Block DARKITE_DOOR = register(new DarkiteDoorBlock());
	public static final Block DARKITE_TRAPDOOR = register(new DarkiteTrapdoorBlock());
	public static final Block IRON_VEILSTONE = register(new IronVeilstoneBlock());
	public static final Block GOLD_VEILSTONE = register(new GoldVeilstoneBlock());
	public static final Block DIAMOND_VEILSTONE = register(new DiamondVeilstoneBlock());
	public static final Block UNSTABLITE_ORE = register(new UnstabliteOreBlock());
	public static final Block UNSTABLITE_BLOCK = register(new UnstabliteBlockBlock());
	public static final Block FLISMOL = register(new FlismolBlock());
	public static final Block TOXMOL = register(new ToxmolBlock());
	public static final Block FLASMOL = register(new FlasmolBlock());
	public static final Block ETHER_CHEST = register(new EtherChestBlock());
	public static final Block UNDERVEIL_DIMENSION_PORTAL = register(new UnderveilDimensionPortalBlock());
	public static final Block FORCE_TNT = register(new ForceTNTBlock());
	public static final Block ETHER_BLOCK = register(new EtherBlockBlock());
	public static final Block BERRYCANE = register(new BerrycaneBlock());
	public static final Block VEILSHROOM = register(new VeilshroomBlock());
	public static final Block VEILDAISY = register(new VeildaisyBlock());
	public static final Block JUMP_PAD = register(new JumpPadBlock());
	public static final Block LANDMINE = register(new LandmineBlock());
	public static final Block ROUGHVEIL_STAIRS = register(new RoughveilStairsBlock());
	public static final Block ROUGHVEIL_SLAB = register(new RoughveilSlabBlock());
	public static final Block ROUGHVEIL_WALL = register(new RoughveilWallBlock());
	public static final Block ROUGHVEIL_PRESSURE_PLATE = register(new RoughveilPressurePlateBlock());
	public static final Block ROUGHVEIL_BUTTON = register(new RoughveilButtonBlock());

	private static Block register(Block block) {
		REGISTRY.add(block);
		return block;
	}

	@SubscribeEvent
	public static void registerBlocks(RegistryEvent.Register<Block> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new Block[0]));
	}

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			AshFenceBlock.registerRenderLayer();
			AshPressurePlateBlock.registerRenderLayer();
			AshButtonBlock.registerRenderLayer();
			AshDoorBlock.registerRenderLayer();
			AshTrapdoorBlock.registerRenderLayer();
			AshSaplingBlock.registerRenderLayer();
			SlipgrassBlock.registerRenderLayer();
			MoslinFenceBlock.registerRenderLayer();
			MoslinPressurePlateBlock.registerRenderLayer();
			MoslinButtonBlock.registerRenderLayer();
			MoslinDoorBlock.registerRenderLayer();
			MoslinTrapdoorBlock.registerRenderLayer();
			MoslinSaplingBlock.registerRenderLayer();
			WetOakFenceBlock.registerRenderLayer();
			WetOakPressurePlateBlock.registerRenderLayer();
			WetOakButtonBlock.registerRenderLayer();
			WetOakDoorBlock.registerRenderLayer();
			WetOakTrapdoorBlock.registerRenderLayer();
			WetOakSaplingBlock.registerRenderLayer();
			RefleiFenceBlock.registerRenderLayer();
			RefleiPressurePlateBlock.registerRenderLayer();
			RefleiButtonBlock.registerRenderLayer();
			RefleiDoorBlock.registerRenderLayer();
			RefleiTrapDoorBlock.registerRenderLayer();
			RefleiSaplingBlock.registerRenderLayer();
			YukoiFenceBlock.registerRenderLayer();
			YukoiPressurePlateBlock.registerRenderLayer();
			YukoiButtonBlock.registerRenderLayer();
			YukoiDoorBlock.registerRenderLayer();
			YukoiTrapDoorBlock.registerRenderLayer();
			YukoiSaplingBlock.registerRenderLayer();
			VeilstoneWallBlock.registerRenderLayer();
			VeilstonePressurePlateBlock.registerRenderLayer();
			VeilstoneButtonBlock.registerRenderLayer();
			DeepveilWallBlock.registerRenderLayer();
			DeepveilPressurePlateBlock.registerRenderLayer();
			DeepveilButtonBlock.registerRenderLayer();
			VeilstoneBricksWallBlock.registerRenderLayer();
			DustsandstoneWallBlock.registerRenderLayer();
			SlidesandstoneBlock.registerRenderLayer();
			SlidesandstoneWallBlock.registerRenderLayer();
			BloodstoneDoorBlock.registerRenderLayer();
			BloodstoneTrapdoorBlock.registerRenderLayer();
			DarkiteDoorBlock.registerRenderLayer();
			DarkiteTrapdoorBlock.registerRenderLayer();
			EtherChestBlock.registerRenderLayer();
			BerrycaneBlock.registerRenderLayer();
			VeilshroomBlock.registerRenderLayer();
			VeildaisyBlock.registerRenderLayer();
			JumpPadBlock.registerRenderLayer();
			LandmineBlock.registerRenderLayer();
		}
	}
}
